const ImageMap = {
  apple: "/Images/Apple.svg",
  avocado: "/Images/Avocado.svg",
  bacon: "/Images/Bacon.svg",
  boiled_egg: "/Images/BoiledEgg.svg",
  bread: "/Images/Bread.svg",
  canned_fish: "/Images/CannedFish.svg",
  carrot: "/Images/Carrot.svg",
  cheese: "/Images/Cheese.svg",
  chocolate: "/Images/Chocolate.svg",
  coconut: "/Images/Coconut.svg",
  coke: "/Images/Coke.svg",
  corn: "/Images/Corn.svg",
  cucumber: "/Images/Cucumber.svg",
  egg_plant: "/Images/EggPlant.svg",
  french_hot_dog: "/Images/FrenchHotDog.svg",
  hot_tea: "/Images/HotTea.svg",
  lemon: "/Images/Lemon.svg",
  lollipop: "/Images/Lollipop.svg",
  nut: "/Images/Nut.svg",
  onion: "/Images/Onion.svg",
  orange: "/Images/Orange.svg",
  peach: "/Images/Peach.svg",
  pear: "/Images/Pear.svg",
  peppers: "/Images/Peppers.svg",
  pomegranate: "/Images/Pomegranate.svg",
  popcorn: "/Images/Popcorn.svg",
  potato: "/Images/Potato.svg",
  salt_pepper: "/Images/SaltPepper.svg",
  snow_flake: "/Images/SnowFlake.svg",
  taco: "/Images/Taco.svg",
  tomato: "/Images/Tomato.svg",
  wine: "/Images/Wine.svg",
};

export default ImageMap;


